### ISSUE TITLE
Resizing window doesn't update follower

### ISSUE THREAD

**Issue by chrism** [echobind/ember-links-with-follower#30]
Hi, thanks for the great addon.

I noticed that resizing the browser didn't update the follower position — is this something I could make a PR for?

**Comment by cball** [comment]
@chrism definitely!

**Comment by chrism** [comment]
@cball hope this is ok for you https://github.com/echobind/ember-links-with-follower/pull/31

**Comment by cball** [comment]
Fixed via #31
