### ISSUE TITLE
Reset on window resize

### ISSUE THREAD

**Issue by samselikoff** [echobind/ember-links-with-follower#35]

**Comment by cball** [comment]
@samselikoff I think you created this just before I released an updated version. Should be working now thanks to @chrism!

**Comment by samselikoff** [comment]
Wonder if transform translate3d is better than width/left here?

Take a look at https://npmcdn.com/#/ on window resizes. Seems smoother.

**Comment by cball** [comment]
Interesting, it definitely is. I wonder how we could best make the transition animation timing on that configurable
