### ISSUE TITLE
Could not find module `ember-getowner-polyfill` imported from `ember-links-with-follower/components/links-with-follower`

### ISSUE THREAD

**Issue by elbeezi** [echobind/ember-links-with-follower#56]
On a vanilla install from ember-cli 2.7.0 (ED and ember both installed at 2.7.0).

Since `ember-getowner-polyfill` is in this addon's `package.json`, I'm not sure why it's not being found (I have little to no experience with addon dev so I don't know at what point code merging happens). If this addon is willing to drop support for versions earlier than the current LTS (2.4.x), the polyfill could be replaced with the `getOwner` included in Ember (or via its shim).

**Comment by cball** [comment]
That's strange. I should have some cycles tomorrow to check it out - it would be kind of a bummer to drop support for early Ember versions on an addon with such simple functionality. Thanks for all the info!

**Comment by alvincrespo** [comment]
This should be taken care of in #80 

Sorry for the late fix here!
