### ISSUE TITLE
Swallows missing link error

### ISSUE THREAD

**Issue by samselikoff** [echobind/ember-links-with-follower#77]
I changed a route name and my app wouldn't render but showed no error. I believe links-with-follower was swallowing the error that "the route 'index' doesn't exist".

Will PR if I get some time.

Thanks for the awesome addon!

**Comment by cball** [comment]
Thanks for the report @samselikoff! I assume since you're getting this on page load that you're using `link-to`'s in the block passed to the component?

**Comment by samselikoff** [comment]
Yep exactly

**Comment by alvincrespo** [comment]
Hmm. Tried to reproduce this quickly in the dummy app of the addon and saw the error propagate. 

![](https://api.monosnap.com/rpc/file/download?id=MtwRrnC06YWE1oAggaZjTUcU02zbEs) 

Going to spin up an Ember app and import this addon to see if there might be a difference when importing.

**Comment by alvincrespo** [comment]
Yeah, so it looks like the addon may not be swallowing up this error:

![](https://api.monosnap.com/rpc/file/download?id=ToUnbEJ0LLCh0AW9nWoXzAjdajBnD0)

But I did notice this error when running an install:

![](https://api.monosnap.com/rpc/file/download?id=DZMrfcQ4ntTnraLAhPVpGGszHPHYIo)

```
loader.js:219Uncaught Error: Could not find module `ember-getowner-polyfill` imported from `ember-links-with-follower/components/links-with-follower`
```

The solution there is to move the `ember-getowner-polyfill` addon into the `dependencies` section of our package.json.

**Comment by alvincrespo** [comment]
Patched up the other error in #79 

@samselikoff When you get a chance, can you share with us your dependencies? We're thinking there might be another addon that could be conflicting with the internals of the component.

**Comment by samselikoff** [comment]
Yep, checking now 👍

**Comment by samselikoff** [comment]
Couldn't reproduce in a Twiddle (ran into get owner polyfill issue). Here are my app's deps:

```
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-cli": "2.7.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-chartist": "1.1.0",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-deploy": "1.0.0-beta.1",
    "ember-cli-deploy-front-end-builds-pack": "0.0.7",
    "ember-cli-gravatar": "3.6.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-moment-shim": "2.0.0",
    "ember-cli-qunit": "^2.0.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "5.4.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-component-css": "0.2.0-beta.6",
    "ember-composable-helpers": "1.0.0",
    "ember-concurrency": "0.7.8",
    "ember-cp-validations": "3.0.0-beta.4",
    "ember-data": "^2.7.0",
    "ember-elsewhere": "0.3.0",
    "ember-export-application-global": "^1.0.5",
    "ember-file-upload": "ryanto/ember-file-upload",
    "ember-font-awesome": "2.2.0",
    "ember-links-with-follower": "0.2.6",
    "ember-load-initializers": "^0.5.1",
    "ember-moment": "7.0.0-beta.3",
    "ember-remarkable": "3.1.2",
    "ember-resolver": "^2.0.3",
    "ember-sortable": "1.8.1",
    "ember-truth-helpers": "1.2.0",
    "loader.js": "^4.0.1"
  }
```

**Comment by cball** [comment]
Tried creating a Twiddle but was playing addon vs dependency wack-a-mole, so I generated an app with the dependencies (https://github.com/cball/links-with-follower-invalid-route-bug).

I do get a white screen but the error shows in console. @samselikoff any further insight you might have? App specific error handler or something that might be also hooking into the router's `willTransition` event?

**Comment by samselikoff** [comment]
Unable to recreate in a sandox, can close this for now and revisit if/when I have time.

Thanks yall!

**Comment by cball** [comment]
👍  anytime!
